source 'https://rubygems.org'
ruby '2.1.5'

gem 'kafka-consumer'
gem 'json'
gem 'dotenv'
gem 'octocore', '~> 0.0.2', '>= 0.0.2'
gem 'hooks'
gem 'god'
gem 'octorecommender'
gem 'daemons'
gem 'octonotification'
